source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec', :require => 'spec'
gem 'httparty'
gem 'pry'
gem 'jsonpath'
gem 'gherkin'
gem 'json-minify'
gem 'faker', '1.9.2'  
gem 'cpf_faker'
gem "rubocop"
