source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec', :require => 'spec'
gem 'httparty'
gem 'pry'
gem 'jsonpath'
gem 'uuid'
gem 'test-unit'
gem 'minitest'
gem 'xpath'
gem 'gherkin'
gem 'json-minify'
gem 'faker'
gem 'cpf_faker'
gem "rubocop"
