wirecard:
  usr: 'YFZIKTEDWJWD0NOYMCHXGIOGXUYBFZKJ'
  pass: '0CRWE94W1IRBS2AGN2KRZJEW48EJ8UT05QR4ACT2'

conta_sandbox:
  usr: 'edson.pita.sp@gmail.com'
  pass: 'cervejaipa'

# usr: ${user.name}
# variavel de ambiente
